"""Large word & quote library for dynamic typing text generation."""

COMMON_WORDS = [
    "the", "be", "of", "and", "a", "to", "in", "he", "have", "it", "that", "for",
    "they", "with", "as", "not", "on", "she", "at", "by", "this", "we", "you", "do",
    "but", "from", "or", "which", "one", "would", "all", "will", "there", "say",
    "who", "make", "when", "can", "more", "if", "no", "man", "out", "other", "so",
    "what", "time", "up", "go", "about", "than", "into", "could", "state", "only",
    "new", "year", "some", "take", "come", "these", "know", "see", "use", "get",
    "like", "then", "first", "any", "work", "now", "may", "such", "give", "over",
    "think", "most", "even", "find", "day", "also", "after", "way", "many", "must",
    "look", "before", "great", "back", "through", "long", "where", "much", "should",
    "well", "people", "down", "own", "just", "because", "good", "each", "those",
    "feel", "seem", "how", "high", "too", "place", "little", "world", "very", "still",
    "nation", "hand", "old", "life", "tell", "write", "become", "here", "show",
    "house", "both", "between", "need", "mean", "call", "develop", "under", "last",
    "right", "move", "thing", "general", "school", "never", "same", "another", "begin",
    "while", "number", "part", "turn", "real", "leave", "might", "want", "point",
    "form", "off", "child", "few", "small", "since", "against", "ask", "late", "home",
    "interest", "large", "person", "end", "open", "public", "follow", "during", "present",
    "without", "again", "hold", "govern", "around", "possible", "head", "consider",
    "word", "program", "problem", "however", "lead", "system", "set", "order", "eye",
    "plan", "run", "keep", "face", "fact", "group", "play", "stand", "increase", "early",
    "course", "change", "help", "line", "city", "put", "close", "case", "force", "meet",
    "once", "water", "upon", "war", "build", "hear", "light", "unite", "live", "every",
    "country", "bring", "center", "let", "side", "try", "provide", "continue", "name",
    "certain", "power", "pay", "result", "question", "study", "woman", "member", "until",
    "far", "night", "always", "service", "away", "report", "something", "company",
    "week", "church", "toward", "start", "social", "room", "figure", "nature", "though",
    "young", "less", "enough", "almost", "read", "include", "president", "nothing",
    "yet", "better", "big", "boy", "cost", "business", "value", "second", "why", "clear",
    "expect", "family", "complete", "act", "sense", "mind", "experience", "art", "next",
    "near", "direct", "car", "law", "industry", "important", "girl", "god", "several",
    "matter", "usual", "rather", "per", "often", "kind", "among", "white", "reason",
    "action", "return", "foot", "care", "simple", "within", "love", "human", "along",
    "appear", "doctor", "believe", "speak", "active", "student", "month", "drive",
    "concern", "best", "door", "hope", "example", "inform", "body", "ever", "least",
    "probable", "understand", "reach", "effect", "different", "idea", "whole", "control",
    "condition", "field", "pass", "fall", "note", "special", "talk", "particular",
    "today", "measure", "walk", "teach", "low", "hour", "type", "carry", "rate",
    "remain", "full", "street", "easy", "though", "stop", "fail", "oh", "produce",
    "cut", "space", "wear", "test", "wait", "decide", "low", "spend", "future", "music",
    "common", "answer", "step", "join", "energy", "river", "method", "color", "story",
    "view", "garden", "design", "model", "secret", "future", "season", "travel", "engine",
    "market", "river", "memory", "courage", "wonder", "silence", "shadow", "morning",
]

ADVANCED_WORDS = [
    "ubiquitous", "ephemeral", "serendipity", "quintessential", "cacophony",
    "labyrinthine", "perspicacious", "magnanimous", "obfuscate", "juxtaposition",
    "idiosyncratic", "surreptitious", "ineffable", "mellifluous", "pernicious",
    "egregious", "sycophant", "vicissitude", "garrulous", "obstreperous",
    "recalcitrant", "sesquipedalian", "antediluvian", "circumlocution", "esoteric",
    "fastidious", "grandiloquent", "iconoclast", "languorous", "munificent",
    "nefarious", "ostentatious", "pulchritude", "quixotic", "rambunctious",
    "salubrious", "tenacious", "umbrage", "verisimilitude", "winsome",
    "xenophobia", "zealous", "acquiesce", "belligerent", "capricious",
    "deleterious", "ebullient", "facetious", "gregarious", "harangue",
    "incontrovertible", "jubilant", "kaleidoscope", "lugubrious", "metamorphosis",
    "nonchalant", "obsequious", "paradigm", "querulous", "resplendent",
    "soliloquy", "trepidation", "unscrupulous", "voracious", "wherewithal",
    "algorithm", "asynchronous", "encapsulation", "polymorphism", "refactoring",
    "concurrency", "middleware", "serialization", "abstraction", "deployment",
]

PUNCTUATION = [".", ",", ";", ":", "!", "?", "-", "'"]

QUOTES = [
    {"text": "The only way to do great work is to love what you do. If you haven't found it yet, keep looking and don't settle.", "author": "Steve Jobs"},
    {"text": "Success is not final, failure is not fatal: it is the courage to continue that counts in the long run.", "author": "Winston Churchill"},
    {"text": "In the middle of difficulty lies opportunity. The world is full of obvious things which nobody ever observes.", "author": "Albert Einstein"},
    {"text": "It does not matter how slowly you go as long as you do not stop moving toward your most important goals.", "author": "Confucius"},
    {"text": "The future belongs to those who believe in the beauty of their dreams and are willing to chase them daily.", "author": "Eleanor Roosevelt"},
    {"text": "Whether you think you can, or you think you can't, you are right. Your mindset shapes the entire outcome.", "author": "Henry Ford"},
    {"text": "The best time to plant a tree was twenty years ago. The second best time to start is right now today.", "author": "Chinese Proverb"},
    {"text": "Do not watch the clock; do what it does and simply keep going until you reach the place you imagined.", "author": "Sam Levenson"},
    {"text": "Everything you have ever wanted is sitting on the other side of the fear that quietly holds you back.", "author": "George Addair"},
    {"text": "Believe you can and you are already halfway there. Confidence turns a distant idea into a real plan.", "author": "Theodore Roosevelt"},
    {"text": "Quality is not an act, it is a habit. We are what we repeatedly do, day after day, without exception.", "author": "Aristotle"},
    {"text": "The journey of a thousand miles begins with a single step taken with patience and a calm steady mind.", "author": "Lao Tzu"},
    {"text": "Code is like humor. When you have to explain it, that usually means it is simply not very good code.", "author": "Cory House"},
    {"text": "Simplicity is the soul of efficiency, and the removal of clutter is often the hardest design choice.", "author": "Austin Freeman"},
    {"text": "First, solve the problem. Then, write the code. The hardest bugs hide in assumptions you never tested.", "author": "John Johnson"},
    {"text": "Your time is limited, so do not waste it living someone else's life or chasing someone else's dream.", "author": "Steve Jobs"},
    {"text": "The mind is everything. What you think you become, so guard your thoughts as you would a quiet garden.", "author": "Buddha"},
    {"text": "Happiness is not something ready made. It comes from your own actions and the small choices you make.", "author": "Dalai Lama"},
    {"text": "Life is what happens when you are busy making other plans, so remember to look up and enjoy the view.", "author": "John Lennon"},
    {"text": "The greatest glory in living lies not in never falling, but in rising every single time that we fall.", "author": "Nelson Mandela"},
]
